# Generated by Django 5.1.1 on 2024-09-11 08:36

import ai.models.user
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.EmailField(max_length=50, unique=True, verbose_name='이메일')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='전화번호')),
                ('represent_photo', models.ImageField(blank=True, upload_to='', verbose_name='대표사진')),
                ('registration_card', models.ImageField(blank=True, upload_to='', verbose_name='신분증')),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='SignUp Date')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('agree_push', models.BooleanField(null=True, verbose_name='푸시알림 동의')),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, null=True, related_name='users', to='auth.permission')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
            },
            managers=[
                ('objects', ai.models.user.UserManager()),
            ],
        ),
    ]
