# Generated by Django 5.1.1 on 2024-09-20 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_user_registration_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenaiMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('message', models.TextField(blank=True, null=True, verbose_name='메시지')),
            ],
            options={
                'verbose_name': 'OpenAI 메시지',
                'verbose_name_plural': 'OpenAI 메시지',
            },
        ),
    ]
